trigger:
  - dev
  - master

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: isActive
    displayName: "isActive"
    default: false # value passed to the condition
    type: boolean

  - name: isCleanMode
    displayName: "isCleanMode"
    default: false # value passed to the condition
    type: boolean

variables:
  serviceConnARM: sc-ARM
  resourceGroup: "rg-demo-spring"

stages:
  - stage: CREATE_INFRAESTRUCTURE
    condition: and(eq('${{ parameters.isActive }}', true), eq('${{ parameters.isCleanMode }}', false))

    jobs:
      - job: IAC
        displayName: "Resoruce group and acr"

        steps:

          - task: CopyFiles@2
            displayName: Copying ARM templates
            inputs:
              #SourceFolder: 'IaC\azure_container_registry/'
              Contents: "**/IaC/**"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"

          # - task: AzureResourceManagerTemplateDeployment@3
          #   displayName: "Deploying Container Registry"
          #   inputs:
          #     deploymentScope: "Resource Group"
          #     azureResourceManagerConnection: $(serviceConnARM)
          #     #subscriptionId: '<your-subscription-id>'
          #     action: "Create Or Update Resource Group"
          #     resourceGroupName: $(resourceGroup)
          #     location: "centralus"
          #     templateLocation: "Linked artifact"
          #     csmFile: "$(Build.ArtifactStagingDirectory)/IaC/azure_container_registry/template.json"
          #     csmParametersFile: "$(Build.ArtifactStagingDirectory)/IaC/azure_container_registry/parameters.json"
          #     #overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
          #     deploymentMode: "Incremental"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploying app service"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(serviceConnARM)
              #subscriptionId: '<your-subscription-id>'
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroup)
              location: "centralus"
              templateLocation: "Linked artifact"
              csmFile: "$(Build.ArtifactStagingDirectory)/IaC/app_service/template.json"
              csmParametersFile: "$(Build.ArtifactStagingDirectory)/IaC/app_service/parameters.json"
              #overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
              deploymentMode: "Incremental"

          - task: AzurePowerShell@5
            displayName: 'Deployment App service'
            inputs:
              azureSubscription: $(serviceConnARM)
              ScriptType: 'FilePath'
              ScriptPath: './Deploy-AzTemplate.ps1'
              ScriptArguments: -Location 'centralus' -ResourceGroupName $(resourceGroup) -TemplateFile '$(Build.ArtifactStagingDirectory)/IaC/azure_container_registry/template.json'
              azurePowerShellVersion: 'LatestVersion'

  - stage: CLEAN_RESOURCES
    condition: and(eq('${{ parameters.isActive }}', true), eq('${{ parameters.isCleanMode }}', true))

    jobs:
      - job: IAC
        displayName: "Cleaning process"

        steps:
          - task: AzureCLI@2
            displayName: List resources in the resource group
            inputs:
              azureSubscription: $(serviceConnARM)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az resource list --resource-group $(resourceGroup) --output table

          - task: AzureCLI@2
            displayName: Delete resouce group and all the inside resources
            inputs:
              azureSubscription: $(serviceConnARM)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group delete --name $(resourceGroup) --yes
