pool:
  vmImage: "ubuntu-latest"

parameters:
  # Optional if you want to control the manual execution of the pipeline instead of using trigger branch
  - name: isDeployment
    displayName: "isDeployment"
    default: false
    type: boolean

  # Set true to detroy all created resources
  - name: isCleanup
    displayName: "isCleanup"
    default: false
    type: boolean

variables:
  serviceConnARM: sc-ARM # Service connection to deploy to Azure subscription
  resourceGroupACR: "rg-demo-spring-acr"
  resourceGroupApp: "rg-demo-spring-app"

stages:
  - stage: CREATE_INFRAESTRUCTURE
    condition: and(eq('${{ parameters.isDeployment }}', true), eq('${{ parameters.isCleanup }}', false))

    jobs:
      - job: IAC
        displayName: "Resoruce group and acr"

        steps:
          - task: CopyFiles@2
            displayName: Copying ARM templates
            inputs:
              Contents: "**/IaC/**"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploying Azure Container Registry"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(serviceConnARM)
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupACR)
              location: "centralus"
              templateLocation: "Linked artifact"
              csmFile: "$(Build.ArtifactStagingDirectory)/IaC/azure_container_registry/template.json"
              csmParametersFile: "$(Build.ArtifactStagingDirectory)/IaC/azure_container_registry/parameters.json"
              #overrideParameters: '-parameterName1 $(localVar1) -parameterName2 $(localVar2)'
              deploymentMode: "Incremental"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploying app service"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(serviceConnARM)
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupApp)
              location: "centralus"
              templateLocation: "Linked artifact"
              csmFile: "$(Build.ArtifactStagingDirectory)/IaC/app_service/template.json"
              csmParametersFile: "$(Build.ArtifactStagingDirectory)/IaC/app_service/parameters.json"
              deploymentMode: "Incremental"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Assignment ACR pull role for the app service"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(serviceConnARM)
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupACR)
              location: "centralus"
              templateLocation: "Linked artifact"
              csmFile: "$(Build.ArtifactStagingDirectory)/IaC/app_service/template.json"
              csmParametersFile: "$(Build.ArtifactStagingDirectory)/IaC/role_assignment/parameters.json"
              overrideParameters: '-appServiceResourceGroup $(resourceGroupApp)'
              deploymentMode: "Incremental"

  - stage: CLEAN_RESOURCES
    condition: and(eq('${{ parameters.isDeployment }}', false), eq('${{ parameters.isCleanup }}', true))

    jobs:
      - job: IAC
        displayName: "Cleaning process"

        steps:
          - task: AzureCLI@2
            displayName: List resources in the resource group
            inputs:
              azureSubscription: $(serviceConnARM)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az resource list --resource-group $(resourceGroupACR) --output table
                az resource list --resource-group $(resourceGroupApp) --output table

          - task: AzureCLI@2
            displayName: Delete resouce group and all the inside resources
            inputs:
              azureSubscription: $(serviceConnARM)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az group delete --name $(resourceGroupACR) --yes
                az group delete --name $(resourceGroupApp) --yes
