trigger:
  - dev
  - master

pool: 
  vmImage: 'ubuntu-latest'

variables:
  serviceConnARM: sc-ARM
  HAS_RUN: ${{flag}}
  repository_dev: spring-boot-app/dev
  repository_prod: spring-boot-app/prod
  defaultTag: latest

stages:
  - stage: CREATE_INFRAESTRUCTURE
    condition: and(eq(variables['Build.SourceBranchName'],'dev'), $(HAS_RUN))

    jobs:
      - job: IAC
        displayName: "Resoruce group and acr"

        steps:
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: $(serviceConnARM)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az account show

          - task: CopyFiles@2
            displayName: Copying ARM templates
            inputs:
              SourceFolder: 'IaC\azure_container_registry/'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(serviceConnARM)
              #subscriptionId: '<your-subscription-id>'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'rg-acr-test'
              location: 'centralus'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.ArtifactStagingDirectory)/template.json'
              csmParametersFile: '$(Build.ArtifactStagingDirectory)/parameters.json'
              #overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
              deploymentMode: 'Incremental'


 